# Generated by Django 6.0.7 on 2026-08-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to='venue_maps/'),
        ),
    ]
